# PID values to use for JointControlLocalImpl

viper:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100.0, i: 0.5, d: 5.0}
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 10.0, i: 0.5, d: 1.0}
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 10.0, i: 0.5, d: 1.0}
  joint_6-tool0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6-tool0
    pid: {p: 10, i: 0.0001, d: 0.005}


  # Velocity Controllers ---------------------------------------
  joint_1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_1
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_3
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_4
    pid: {p: 100.0, i: 0.5, d: 1.0}
  joint_5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_5
    pid: {p: 10.0, i: 0.5, d: 1.0}
  joint_6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6
    pid: {p: 10.0, i: 0.5, d: 1.0}
  joint_6-tool0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6-tool0
    pid: {p: 10, i: 0.0001, d: 0.005}
