# PID values to use for ViperJointControlLocalImpl if Joint::SetVelocity()
# is to be used instead of Joint::SetForce().

viper:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 20, i: 1.0, d: 0}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 20, i: 1.0, d: 0}
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 20, i: 1.0, d: 0}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 20, i: 1.0, d: 0}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 20, i: 1.0, d: 0}
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 20, i: 1.0, d: 0}
  joint_6-tool0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6-tool0
    pid: {p: 20, i: 1.0, d: 0}

  # Velocity Controllers ---------------------------------------
  # old values for all: p: 0.8 i: 0.4 d: 0
    # Velocity Controllers ---------------------------------------
  joint_1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_1
    pid: {p: 0.4, i: 0, d: 0}
  joint_2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 0.4, i: 0, d: 0}
  joint_3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_3
    pid: {p: 0.4, i: 0, d: 0}
  joint_4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_4
    pid: {p: 0.4, i: 0, d: 0}
  joint_5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_5
    pid: {p: 0.4, i: 0, d: 0}
  joint_6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6
    pid: {p: 0.4, i: 0, d: 0}
  joint_6-tool0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6-tool0
    pid: {p: 0.4, i: 0, d: 0}
