# PID values to use for JacoJointControlLocalImpl if Joint::SetForce()
# is to be used instead of Joint::SetVelocity().

viper:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 50, i: 0.01, d: 2.5}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100, i: 0.01, d: 5}
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 50, i: 0.01, d: 2.5}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 10, i: 0.01, d: 0.1}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 10, i: 0.01, d: 0.1}
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 10, i: 0.001, d: 0.005}
  joint_6-tool0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6-tool0
    pid: {p: 20, i: 1.0, d: 0}

  # Velocity Controllers ---------------------------------------
  joint_1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_1
    pid: {p: 30, i: 0, d: 0.01}
  joint_2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 80, i: 0, d: 0.01}
  joint_3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_3
    pid: {p: 50, i: 0, d: 0}
  joint_4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_4
    pid: {p: 5, i: 0, d: 0.001}
  joint_5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_5
    pid: {p: 2, i: 0, d: 0.001}
  joint_6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6
    pid: {p: 2, i: 0, d: 0.001}
  joint_6-tool0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6-tool0
    pid: {p: 0.1, i: 0, d: 0}
